version: '3.3'
services:
  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    restart: always
    networks:
      - 'dev'
    ports:
      - '20:20'
      - '21:21'
      - '21100-21110:21100-21110'
    volumes:
      - '/home/docker/vsftpd:/home/vsftpd'
    environment:
      - FTP_USER=user01
      - FTP_PASS=passwd01
      - PASV_ADDRESS=0.0.0.0
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
networks:
  dev:
    external: true
