version: '3.3'

services:
  dnsmasq:
    container_name: dnsmasq
    image: jpillora/dnsmasq
    restart: unless-stopped
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - dev
    ports:
      - 53:53/udp
#      - 8083:8080
    environment:
      - HTTP_USER=hzkoala
      - HTTP_PASS=hz1989315
      
networks:
  dev:
    external: true
