version: '3.3'

services:
  frps:
    container_name: frps
    image: snowdreamtech/frps:0.51.3
    restart: always
    volumes:
      # - '/etc/frp/frps.ini:/etc/frp/frps.ini'
      - './frps.ini:/etc/frp/frps.ini'
    network_mode: host
    