version: '3.3'

services:
  confluence:
    container_name: confluence
    image: atlassian/confluence-server
    restart: always
    volumes:
      - /home/docker/confluence:/var/atlassian/application-data/confluence
    networks:
      - dev
    ports:
      - '8090:8090'
      - '8091:8091'
      
networks:
  dev:
    external: true
