version: '3.3'
services:
  confluence:
    container_name: confluence
    image: atlassian/confluence-server
    restart: always
    networks:
      - 'dev'
    ports:
      - '8090:8090'
      - '8091:8091'
    volumes:
      - '/home/docker/confluence:/var/atlassian/application-data/confluence'
networks:
  dev:
    external: true
