version: '3.3'

services:
  clash:
    container_name: clash
    image: dreamacro/clash
    restart: unless-stopped
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    network_mode: host

  yacd:
    container_name: yacd
    image: haishanh/yacd
    restart: unless-stopped
    networks:
      - dev
    ports: 
      - 7892:80

networks:
  dev:
    external: true
