version: '3'

services:
  db:
    image: mysql/mysql-server:5.6
    restart: unless-stopped
    networks:
      - webstack
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webstack
      MYSQL_USER: webstack
      MYSQL_PASSWORD: webstack
    command: --default-authentication-plugin=mysql_native_password
      
  redis:
    image: redis
    restart: unless-stopped
    networks:
      - webstack
      
  web:
    image: arvon2014/webstack-laravel:v1.2.2
    restart: unless-stopped
    networks:
      webstack:
      dev:
        aliases:
          - webstack
#    ports:
#      - 8001:8000
    depends_on:
      - db
      - redis
    environment:
      LOGIN_COPTCHA: "false"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: webstack
      DB_USERNAME: webstack
      DB_PASSWORD: webstack
    command: ['/entrypoint.sh','server']

networks:
  webstack:
  dev:
    external: true
