version: '3.3'

services:
  memcached:
    container_name: memcached
    image: memcached
    restart: always
    networks:
      - dev
    ports:
      - 11211:11211
      
networks:
  dev:
    external: true
