version: '3.3'

services:
  v2ray:
    container_name: v2ray
    image: teddysun/v2ray
    restart: unless-stopped
    volumes:
      # - /etc/v2ray/config.json:/etc/v2ray/config.json
      - ./config.json:/etc/v2ray/config.json
    network_mode: host
    