version: '3'
services:
  baota:
    container_name: baota
    image: pch18/baota
    restart: always
    networks:
      dev:
        aliases:
          - mysql
    ports:
      - '888:888'
      - '8888:8888'
#    volumes:
#      - '/home/docker/baota:/www'
#      - '/home/docker/baota/wwwroot:/www/wwwroot'
    shm_size: '1g'
networks:
  dev:
    external: true
