version: '3.3'

services:
  dnsmasq:
    container_name: dnsmasq
    image: jcowey/dnsmasq-arm:1.0.0
    restart: always
    volumes:
      - ../dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - dev
    ports:
      - '53:53'
      - '53/udp:53/udp'
      - '8083:8080'
    environment:
      - HTTP_USER=hzkoala
      - HTTP_PASS=hz1989315
      
networks:
  dev:
    external: true
