version: '3.3'

services:
  shiori:
    container_name: shiori
    image: radhifadlillah/shiori
    restart: always
    volumes:
      - /home/docker/shiori:/srv/shiori
    networks:
      - dev
#    ports:
#      - 8080:8080
      
networks:
  dev:
    external: true
