version: '3.3'
services:
  shiori:
    container_name: shiori
    image: radhifadlillah/shiori
    restart: always
    networks:
      - 'dev'
    ports:
      - '8080:8080'
    volumes:
      - '/home/docker/shiori:/srv/shiori'
networks:
  dev:
    external: true
