version: '3.3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins
    restart: unless-stopped
    volumes:
      - /home/docker/jenkins:/var/jenkins_home
    networks:
      - dev
#    ports:
#      - '8080:8080'
#      - '50000:50000'
      
networks:
  dev:
    external: true