version: '3.3'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: always
    networks:
      - 'dev'
    ports:
      - '8123:8123'
    volumes:
      - '/home/docker/home-assistant/config:/config'
networks:
  dev:
    external: true