version: '3.3'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    restart: always
    volumes:
      - /home/docker/home-assistant/config:/config
    networks:
      - dev
#    ports:
#      - 8123:8123
      
networks:
  dev:
    external: true