version: '3'
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    networks:
      - 'dev'
    ports:
      - '2222:22'
    volumes:
      - '/etc/gitlab:/etc/gitlab'
      - '/home/docker/gitlab:/var/opt/gitlab'
networks:
  dev:
    external: true