version: '3.3'

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: unless-stopped
    volumes:
      - /etc/gitlab:/etc/gitlab
      - /home/docker/gitlab:/var/opt/gitlab
    networks:
      - dev
#    ports:
#      - 1022:22
#      - 1080:80
#      - 1443:443
      
networks:
  dev:
    external: true
