version: '3.3'

services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    restart: unless-stopped
    volumes:
      - /home/docker/mysql/data:/var/lib/mysql
      #- /home/docker/mysql/conf/mysqld.conf:/etc/mysql/conf.d/mysqld.conf
      - ./mysqld.conf:/etc/mysql/conf.d/mysqld.conf
    networks:
      - dev
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    privileged: true
    
networks:
  dev:
    external: true
