version: '3.3'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - 'dev'
    ports:
      - '80:80'
    volumes:
      - '/home/docker/nginx/app:/app'
      - '/home/docker/nginx/logs:/etc/nginx/logs'
      - '/home/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf'
      #- 'nginx.conf:/etc/nginx/nginx.conf'
    privileged: true
networks:
  dev:
    external: true