version: '3.3'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:1.24.2
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/portainer:/data
    networks:
      - dev
    ports:
      - '8000:8000'
      - '9000:9000'
      
networks:
  dev:
    external: true
