version: '3.3'

services:
  bind:
    container_name: bind
    image: sameersbn/bind
    restart: always
    volumes:
      - /home/docker/bind:/data
    networks:
      - dev
    ports:
      - 53:53/udp
#      - 10000:10000
      
networks:
  dev:
    external: true
