version: '3.3'
services:
  svn:
    container_name: svn
    image: psgarethflowers/svn-server
    restart: always
    networks:
      - 'dev'
    ports:
      - '3690:3690'
    volumes:
      - '/home/docker/svn:/var/opt/svn'
networks:
  dev:
    external: true
