version: '3.3'

services:
  web:
    image: jayfong/yapi
    restart: unless-stopped
    volumes:
      - ./config.js:/yapi/config.js
    networks:
      yapi:
      dev:
        aliases:
          - yapi
#    ports:
#      - 3000:3000

  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/docker/yapi/mongodb/data:/data/db
      - /home/docker/yapi/mongodb/log:/var/log/mongodb
    networks:
      - yapi
#    ports:
#      - 27017:27017
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=root

networks:
  yapi:
  dev:
    external: true
