version: '3.3'

services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    networks:
      - dev
    ports:
#      - '80:80'
      - '81:81'
#      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  dev:
    external: true