version: '3.3'

services:
  wiz:
    container_name: wiz
    image: wiznote/wizserver
    restart: unless-stopped
    volumes:
      - /home/docker/wiz:/wiz/storage
      - /etc/localtime:/etc/localtime
    networks:
      - dev
#    ports:
#      - 81:80
#      - 9269:9269/udp
      
networks:
  dev:
    external: true
